#!/bin/bash
baseDir="$HOME/Documents/Syncrop"
packageName="syncrop"
mfHome="$HOME/Documents/Syncrop/Syncrop/JarCreation"

path="$HOME/Documents/Syncrop/Jars" #$HOME/Documents/Syncrop
linux_path="$HOME/Documents/Syncrop/fakeroot/usr/lib/syncrop"

function createJars {
	cd "$HOME/Documents/Syncrop/Syncrop/SyncropGUI/bin"
	jar cfm "$path/SyncropGUI.jar" "$mfHome/SyncropGUI_MANIFEST.MF" *
	
	cd "$HOME/Documents/Syncrop/Syncrop/SyncropDaemon/bin"
	
	jar cfm "$path/Syncrop.jar" "$mfHome/Syncrop_MANIFEST.MF" * 
	
	cd ../../Server/bin
	jar cf "$path/Client.jar" client/* logger/* message/*
	jar cf "$path/Server.jar" server/* logger/* message/*
	
}

function package {
	#############Linux################
	cd $baseDir;
	version=`java -jar "$path/Syncrop.jar" -v`
	sed -i "4s/.*/pkgver='$version'/" PKGBUILD
    tar -pczf "syncrop.tar.gz" fakeroot
	
}

function commit {
	git commit -a -m "$message"
	echo "pushing changes to git"
	git push
}

createJars
message=$(zenity --entry)
package
commit
